version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

  app:
    build: ./data
    volumes:
      - ./data:/usr/src/data
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=citizix_db
      - DB_USER=citizix_user
      - DB_PASS=S3cret
    restart: "on-failure"

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=citizix_db
      - DB_USER=citizix_user
      - DB_PASS=S3cret
    ports:
      - 5000:5000
    restart: "on-failure"

  frontend:
    build: ./react-app
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: "on-failure"